angular.module('ngApp.values.Commmon', [])

.value('Comm', {
  languages: [
    {value: 'en', caption: /* i18nextract */'English'},
    {value: 'ru', caption: /* i18nextract */'Русский'}
  ],
  timezones: [
    {value: 'Pacific/Apia', caption: /* i18nextract */'(GMT-11:00) Midway Island, Samoa'},
    {value: 'Pacific/Honolulu', caption: /* i18nextract */'(GMT-10:00) Hawaii'},
    {value: 'America/Anchorage', caption: /* i18nextract */'(GMT-09:00) Alaska'},
    {value: 'America/Los_Angeles', caption: /* i18nextract */'(GMT-08:00) Tijuana, Baja California'},
    {value: 'America/Phoenix', caption: /* i18nextract */'(GMT-07:00) Arizona'},
    {value: 'America/Denver', caption: /* i18nextract */'(GMT-07:00) Pacific Time (U.S. & Canada)'},
    {value: 'America/Chihuahua', caption: /* i18nextract */'(GMT-07:00) Chihuahua, La Paz, Mazatlan'},
    {value: 'America/Managua', caption: /* i18nextract */'(GMT-06:00) Central America'},
    {value: 'America/Regina', caption: /* i18nextract */'(GMT-06:00) Saskatchewan'},
    {value: 'America/Mexico_City', caption: /* i18nextract */'(GMT-06:00) Gvalahara, Mexico City, Monterrey'},
    {value: 'America/Chicago', caption: /* i18nextract */'(GMT-06:00) Central Time (U.S. & Canada)'},
    {value: 'America/Indianapolis', caption: /* i18nextract */'(GMT-05:00) Indiana (East)'},
    {value: 'America/Bogota', caption: /* i18nextract */'(GMT-05:00) Bogota, Lima, Quito, Rio Branco'},
    {value: 'America/New_York', caption: /* i18nextract */'(GMT-05:00) Eastern Time (U.S. & Canada)'},
    {value: 'America/Caracas', caption: /* i18nextract */'(GMT-04:00) Caracas, La Paz'},
    {value: 'America/Santiago', caption: /* i18nextract */'(GMT-04:00) Santiago'},
    {value: 'America/Halifax', caption: /* i18nextract */'(GMT-04:00) Atlantic Time (Canada)'},
    {value: 'America/St_Johns', caption: /* i18nextract */'(GMT-03:30) Newfoundland'},
    {value: 'America/Buenos_Aires', caption: /* i18nextract */'(GMT-03:00) Buenos Aires, Georgetown'},
    {value: 'America/Godthab', caption: /* i18nextract */'(GMT-03:00) Greenland'},
    {value: 'America/Sao_Paulo', caption: /* i18nextract */'(GMT-03:00) Brazil'},
    {value: 'America/Noronha', caption: /* i18nextract */'(GMT-02:00) Mid-Atlantic'},
    {value: 'Atlantic/Cape_Verde', caption: /* i18nextract */'(GMT-01:00) Cape Verde Islands'},
    {value: 'Atlantic/Azores', caption: /* i18nextract */'(GMT-01:00) Azores'},
    {value: 'Africa/Casablanca', caption: /* i18nextract */'(GMT) Casablanca, Monrovia'},
    {value: 'Europe/London', caption: /* i18nextract */'(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London'},
    {value: 'Africa/Lagos', caption: /* i18nextract */'(GMT+01:00) West Central Africa'},
    {value: 'Europe/Berlin', caption: /* i18nextract */'(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna'},
    {value: 'Europe/Paris', caption: /* i18nextract */'(GMT+01:00) Brussels, Copenhagen, Madrid, Paris'},
    {value: 'Europe/Sarajevo', caption: /* i18nextract */'(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb'},
    {value: 'Europe/Belgrade', caption: /* i18nextract */'(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague'},
    {value: 'Africa/Johannesburg', caption: /* i18nextract */'(GMT+02:00) Harare, Pretoria'},
    {value: 'Asia/Jerusalem', caption: /* i18nextract */'(GMT+02:00) Jerusalem'},
    {value: 'Europe/Istanbul', caption: /* i18nextract */'(GMT+02:00) Athens, Bucharest, Istanbul'},
    {value: 'Europe/Helsinki', caption: /* i18nextract */'(GMT+02:00) Helsinki, Riga, Sofia, Tallinn, Vilnius'},
    {value: 'Africa/Cairo', caption: /* i18nextract */'(GMT+02:00) Cairo'},
    {value: 'Europe/Bucharest', caption: /* i18nextract */'(GMT+02:00) Bucharest'},
    {value: 'Europe/Kiev', caption: /* i18nextract */'(GMT+02:00) Kiev'},
    {value: 'Europe/Minsk', caption: /* i18nextract */'(GMT+03:00) Minsk, Kaliningrad'},
    {value: 'Africa/Nairobi', caption: /* i18nextract */'(GMT+03:00) Nairobi'},
    {value: 'Asia/Riyadh', caption: /* i18nextract */'(GMT+03:00) Kuwait, Riyadh'},
    {value: 'Asia/Baghdad', caption: /* i18nextract */'(GMT+03:00) Baghdad'},
    {value: 'Europe/Moscow', caption: /* i18nextract */'(GMT+03:00) Moscow, St. Petersburg, Volgograd, Samara'},
    {value: 'Asia/Tehran', caption: /* i18nextract */'(GMT+03:30) Tehran'},
    {value: 'Asia/Muscat', caption: /* i18nextract */'(GMT+04:00) Abu Dhabi, Muscat'},
    {value: 'Asia/Tbilisi', caption: /* i18nextract */'(GMT+04:00) Baku, Tbilisi, Yerevan'},
    {value: 'Asia/Kabul', caption: /* i18nextract */'(GMT+04:30) Kabul'},
    {value: 'Asia/Karachi', caption: /* i18nextract */'(GMT+05:00) Islamabad, Karachi, Tashkent'},
    {value: 'Asia/Aqtobe', caption: /* i18nextract */'(GMT+05:00) Aktobe'},
    {value: 'Asia/Calcutta', caption: /* i18nextract */'(GMT+05:30) Bombay, Calcutta, Madras, New Delhi'},
    {value: 'Asia/Katmandu', caption: /* i18nextract */'(GMT+05:45) Katmandu'},
    {value: 'Asia/Yekaterinburg', caption: /* i18nextract */'(GMT+06:00) Yekaterinburg'},
    {value: 'Asia/Colombo', caption: /* i18nextract */'(GMT+06:00) Sri Jayawardenepura'},
    {value: 'Asia/Dhaka', caption: /* i18nextract */'(GMT+06:00) Dhaka'},
    {value: 'Asia/Almaty', caption: /* i18nextract */'(GMT+06:00) Astana, Almaty'},
    {value: 'Asia/Rangoon', caption: /* i18nextract */'(GMT+06:30) Yangon (Rangoon)'},
    {value: 'Asia/Novosibirsk', caption: /* i18nextract */'(GMT+07:00) Novosibirsk'},
    {value: 'Asia/Bangkok', caption: /* i18nextract */'(GMT+07:00) Bangkok, Jakarta, Hanoi'},
    {value: 'Asia/Krasnoyarsk', caption: /* i18nextract */'(GMT+08:00) Krasnoyarsk'},
    {value: 'Australia/Perth', caption: /* i18nextract */'(GMT+08:00) Perth'},
    {value: 'Asia/Taipei', caption: /* i18nextract */'(GMT+08:00) Taipei'},
    {value: 'Asia/Singapore', caption: /* i18nextract */'(GMT+08:00) Kuala Lumpur, Singapore'},
    {value: 'Asia/Hong_Kong', caption: /* i18nextract */'(GMT+08:00) Beijing, Hong Kong, Urumqi'},
    {value: 'Asia/Irkutsk', caption: /* i18nextract */'(GMT+09:00) Irkutsk'},
    {value: 'Asia/Tokyo', caption: /* i18nextract */'(GMT+09:00) Osaka, Sapporo, Tokyo'},
    {value: 'Asia/Seoul', caption: /* i18nextract */'(GMT+09:00) Seoul'},
    {value: 'Australia/Darwin', caption: /* i18nextract */'(GMT+09:30) Darwin'},
    {value: 'Australia/Adelaide', caption: /* i18nextract */'(GMT+09:30) Adelaide'},
    {value: 'Asia/Yakutsk', caption: /* i18nextract */'(GMT+10:00) Yakutsk'},
    {value: 'Pacific/Guam', caption: /* i18nextract */'(GMT+10:00) Guam, Port Moresby'},
    {value: 'Australia/Brisbane', caption: /* i18nextract */'(GMT+10:00) Brisbane'},
    {value: 'Australia/Hobart', caption: /* i18nextract */'(GMT+10:00) Hobart'},
    {value: 'Australia/Sydney', caption: /* i18nextract */'(GMT+10:00) Canberra, Melbourne, Sydney'},
    {value: 'Asia/Vladivostok', caption: /* i18nextract */'(GMT+11:00) Vladivostok, Sakhalin'},
    {value: 'Asia/Magadan', caption: /* i18nextract */'(GMT+12:00) Chukotka, Kamchatka, Magadan'},
    {value: 'Pacific/Fiji', caption: /* i18nextract */'(GMT+12:00) Fiji, Marshall Islands'},
    {value: 'Pacific/Auckland', caption: /* i18nextract */'(GMT+12:00) Auckland, Wellington'},
    {value: 'Pacific/Tongatapu', caption: /* i18nextract */'(GMT+13:00) Nukuʻalofa'}
  ]
})

;
